#
# Copyright (C) 2020-2024 Arm Limited or its affiliates and Contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
name: verify-cmsis-example-action
description: GitHub action to verify if a CMSIS example project is compatible with CMSIS tools
inputs:
  branch:
    description: "Branch to get the project from"
    required: false
    default: ${{ github.head_ref }}
  project-file:
    description: "Path to the project to publish (file with `.csolution.yml` extension) (required) "
    required: true
  API_TOKEN:
    description: "API token for accessing online services"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install publishing tool
      shell: bash
      run: |
        echo "deb [trusted=yes] https://artifacts.tools.arm.com/tools-deb bionic main" | sudo tee -a /etc/apt/sources.list.d/artifactory.list          
        sudo apt-get update
        sudo apt install -y verify-cmsis-example-sdk
        sudo rm /etc/apt/sources.list.d/artifactory.list  
        sudo apt-get clean
    - name: Verify project
      run: |
        verify-cmsis-example-sdk verify --project-dir ${{ github.workspace }} --project-path ${{ inputs.project-file }} --out-dir out --api-key ${{ inputs.API_TOKEN }} --log-error 2
      shell: bash
    - name: Upload any artifacts
      uses: actions/upload-artifact@v4
      with:
        name: generated-outputs
        if-no-files-found: ignore
        path: out

