#
# Copyright (C) 2020-2024 Arm Limited or its affiliates and Contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
name: CI

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ inputs.branch || github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    tags-ignore:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  verify-cmsis-example-action-test-1:
    name: Integration Tests 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # this repo
      - uses: actions/checkout@v4 # test repo
        with: 
          repository: Arm-Examples/Hello_LPCXpresso55S69
          path: test
      - uses: ./
        name: Import Project Action
        with:
          branch: main
          project-file: ./test/hello.csolution.yml
          output-artifact: test-1
          API_TOKEN: ${{ secrets.API_TOKEN }}
          
  verify-cmsis-example-action-test-2:
    name: Integration Tests 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # this repo
      - uses: actions/checkout@v4 # test repo
        with: 
          repository: Arm-Examples/Hello_LPCXpresso55S69
          path: test2
      - uses: ./
        name: Import Project Action
        with:
          branch: main
          project-file: ./MLOps.csolution.yml
          project-directory: ./test2/QeexoAutoML
          output-artifact: test-2
          API_TOKEN: ${{ secrets.API_TOKEN }}
